"""Standard RGB fiducial geometry and calibrated pose recovery.

The learned pose head is a useful experiment, but its held-out transfer error
is too large for a millimetre-scale rack.  The production path is an ArUco
service datum with known geometry and a calibrated PnP solve.  This module has
no simulator dependency and never receives a module pose; runtime inputs are an
RGB image and the camera intrinsic matrix.
"""

from __future__ import annotations

from dataclasses import dataclass

import cv2
import numpy as np

FIDUCIAL_DICTIONARY = cv2.aruco.DICT_4X4_50
FIDUCIAL_MARKER_ID = 23
# **The service plate lies on the module's top face, and it used to float above
# it.**
#
# ``FIDUCIAL_TAG_CENTER_M`` was (0, -0.015, 0.100): a tilted plate pinned
# 100 mm above the module's centre plane, angled to face the fixed overview
# camera. That was defensible while the module was 35 mm thick and it is not
# now that it is 20 mm -- the plate stood 90 mm clear of the body on nothing,
# which is not a service plate, it is a billboard.
#
# It is now flush on the top face, tag frame aligned with the module frame, and
# sized to fit inside the 130 mm width with its quiet zone. The overview camera
# at (-0.55, -0.65, 1.15) looks down on the rack, so a top-face plate is inside
# its view; what changes is the incidence angle, and that is a perception
# question rather than a geometry one.
#
# **This invalidates evidence/fiducial_rgbd_service_plate.json**, which was
# certified against the old plate pose. Perception has to be re-certified on
# this one; it needs re-certifying anyway, because the module it measures
# changed size.
FIDUCIAL_TAG_SIZE_M = 0.090
FIDUCIAL_QUIET_ZONE_SIZE_M = 0.120
#: Half the module's 20 mm thickness, plus a millimetre of plate standoff.
FIDUCIAL_TAG_CENTER_M = (0.0, 0.0, 0.011)
# Columns are the tag-frame x/y/normal axes expressed in the module frame. The
# plate lies in the module's own xy plane with its normal up, so this is the
# identity and the tag's rows read along the module's length.
FIDUCIAL_TAG_BASIS_MODULE: tuple[tuple[float, float, float], ...] = (
    (1.0, 0.0, 0.0),
    (0.0, 1.0, 0.0),
    (0.0, 0.0, 1.0),
)
FIDUCIAL_TAG_ROTATION_MODULE_FROM_TAG_WXYZ = (1.0, 0.0, 0.0, 0.0)

# The exact 6x6 raster generated by OpenCV for DICT_4X4_50 marker 23: one black
# border cell around the four data rows.  The USD spawner consumes this array to
# build code-native geometry, so deployment cannot silently use a different tag
# from the one the detector expects.
FIDUCIAL_TAG_BITS: tuple[tuple[int, ...], ...] = (
    (0, 0, 0, 0, 0, 0),
    (0, 1, 1, 0, 1, 0),
    (0, 1, 1, 0, 1, 0),
    (0, 1, 0, 0, 0, 0),
    (0, 0, 0, 1, 0, 0),
    (0, 0, 0, 0, 0, 0),
)

_HALF_TAG = 0.5 * FIDUCIAL_TAG_SIZE_M
_TAG_CENTER = np.asarray(FIDUCIAL_TAG_CENTER_M, dtype=np.float64)
_ROTATION_MODULE_FROM_TAG = np.asarray(FIDUCIAL_TAG_BASIS_MODULE, dtype=np.float64)
# ArUco returns canonical top-left, top-right, bottom-right, bottom-left image
# corners.  The authored tag frame is right-handed with +y pointing toward the
# raster top (image rows grow downward), so the corresponding object corners
# use +y for the two top corners.  Keeping this convention explicit prevents a
# visually plausible but undecodable vertically mirrored marker.
_OBJECT_POINTS = np.asarray(
    (
        (-_HALF_TAG, _HALF_TAG, 0.0),
        (_HALF_TAG, _HALF_TAG, 0.0),
        (_HALF_TAG, -_HALF_TAG, 0.0),
        (-_HALF_TAG, -_HALF_TAG, 0.0),
    ),
    dtype=np.float64,
)


@dataclass(frozen=True)
class FiducialPose:
    """One calibrated object-to-camera pose recovered from RGB."""

    position_camera_m: np.ndarray
    rotation_camera_from_object: np.ndarray
    image_points_px: np.ndarray
    reprojection_error_px: float
    confidence: float


def _marker_corners(image_rgb: np.ndarray) -> np.ndarray:
    image = np.asarray(image_rgb)
    if image.ndim != 3 or image.shape[2] < 3:
        raise ValueError(f"RGB image must have shape (height, width, channels), got {image.shape}")
    rgb = image[..., :3]
    if not np.isfinite(rgb).all():
        raise ValueError("RGB image contains non-finite pixels")
    if np.issubdtype(rgb.dtype, np.floating):
        rgb = np.clip(np.rint(rgb * 255.0), 0.0, 255.0).astype(np.uint8)
    elif rgb.dtype != np.uint8:
        rgb = rgb.astype(np.uint8)
    gray = cv2.cvtColor(rgb, cv2.COLOR_RGB2GRAY)
    parameters = cv2.aruco.DetectorParameters()
    parameters.cornerRefinementMethod = cv2.aruco.CORNER_REFINE_SUBPIX
    parameters.minMarkerPerimeterRate = 0.02
    detector = cv2.aruco.ArucoDetector(
        cv2.aruco.getPredefinedDictionary(FIDUCIAL_DICTIONARY),
        parameters,
    )
    corners, identifiers, _ = detector.detectMarkers(gray)
    if identifiers is None:
        raise RuntimeError(f"ArUco service datum {FIDUCIAL_MARKER_ID} was not detected")
    matches = np.flatnonzero(identifiers.reshape(-1) == FIDUCIAL_MARKER_ID)
    if matches.size != 1:
        raise RuntimeError(f"expected one ArUco service datum {FIDUCIAL_MARKER_ID}, detected {int(matches.size)}")
    return np.asarray(corners[int(matches[0])], dtype=np.float64).reshape(4, 2)


def _refine_tag_pose_from_depth(
    image_points: np.ndarray,
    depth_image_plane_m: np.ndarray,
    intrinsic: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, float]:
    """Fit the known tag plane to metric RGB-D samples inside its border."""

    depth = np.asarray(depth_image_plane_m, dtype=np.float64).squeeze()
    if depth.ndim != 2:
        raise ValueError(f"image-plane depth must have shape (height, width), got {depth.shape}")
    # Project a dense interior grid through the detected tag homography.  The
    # 12% margin keeps samples away from foreground/background edge pixels.
    extent = 0.38 * FIDUCIAL_TAG_SIZE_M
    axis = np.linspace(-extent, extent, 9, dtype=np.float64)
    object_xy = np.asarray([(x, y) for y in axis[::-1] for x in axis], dtype=np.float64)
    homography = cv2.getPerspectiveTransform(_OBJECT_POINTS[:, :2].astype(np.float32), image_points.astype(np.float32))
    pixels = cv2.perspectiveTransform(object_xy[None].astype(np.float32), homography)[0].astype(np.float64)
    u = np.rint(pixels[:, 0]).astype(np.int64)
    v = np.rint(pixels[:, 1]).astype(np.int64)
    valid = (u >= 0) & (u < depth.shape[1]) & (v >= 0) & (v < depth.shape[0])
    z = np.full(len(pixels), np.nan, dtype=np.float64)
    z[valid] = depth[v[valid], u[valid]]
    valid &= np.isfinite(z) & (z > 0.05)
    if int(valid.sum()) < 24:
        raise RuntimeError("fiducial RGB-D refinement has fewer than 24 valid interior samples")

    pixels = pixels[valid]
    object_points = np.column_stack((object_xy[valid], np.zeros(int(valid.sum()))))
    z = z[valid]
    camera_points = np.column_stack(
        (
            (pixels[:, 0] - intrinsic[0, 2]) * z / intrinsic[0, 0],
            (pixels[:, 1] - intrinsic[1, 2]) * z / intrinsic[1, 1],
            z,
        )
    )
    object_centroid = object_points.mean(axis=0)
    camera_centroid = camera_points.mean(axis=0)
    covariance = (object_points - object_centroid).T @ (camera_points - camera_centroid)
    left, _, right_t = np.linalg.svd(covariance)
    rotation = right_t.T @ left.T
    if np.linalg.det(rotation) < 0.0:
        right_t[-1] *= -1.0
        rotation = right_t.T @ left.T
    translation = camera_centroid - rotation @ object_centroid
    residual = np.linalg.norm((rotation @ object_points.T).T + translation - camera_points, axis=1)
    fit_rms = float(np.sqrt(np.mean(np.square(residual))))
    if not np.isfinite(fit_rms) or fit_rms > 0.006:
        raise RuntimeError(f"fiducial RGB-D plane fit {1_000.0 * fit_rms:.2f} mm exceeds 6 mm")
    return rotation, translation, fit_rms


def estimate_fiducial_pose(
    image_rgb: np.ndarray,
    intrinsic_matrix: np.ndarray,
    depth_image_plane_m: np.ndarray | None = None,
) -> FiducialPose:
    """Estimate the module pose in the OpenCV/ROS camera frame.

    RGB-only PnP remains available for ordinary calibrated cameras.  When
    registered metric depth is present, the final pose is a multi-point RGB-D
    plane fit, which is the deployed path used by this workcell.
    """

    intrinsic = np.asarray(intrinsic_matrix, dtype=np.float64)
    if intrinsic.shape != (3, 3) or not np.isfinite(intrinsic).all():
        raise ValueError("camera intrinsic matrix must be finite with shape (3, 3)")
    image_points = _marker_corners(image_rgb)
    solved, rotation_vector, translation = cv2.solvePnP(
        _OBJECT_POINTS,
        image_points,
        intrinsic,
        np.zeros((4, 1), dtype=np.float64),
        flags=cv2.SOLVEPNP_IPPE,
    )
    if not solved:
        raise RuntimeError("calibrated fiducial PnP did not converge")
    rotation_camera_from_tag, _ = cv2.Rodrigues(rotation_vector)
    depth_fit_rms: float | None = None
    if depth_image_plane_m is not None:
        rotation_camera_from_tag, tag_position, depth_fit_rms = _refine_tag_pose_from_depth(
            image_points, depth_image_plane_m, intrinsic
        )
        translation = tag_position.reshape(3, 1)
    rotation = rotation_camera_from_tag @ _ROTATION_MODULE_FROM_TAG.T
    position = translation.reshape(3) - rotation @ _TAG_CENTER
    if not np.isfinite(rotation).all() or not np.isfinite(position).all() or position[2] <= 0.0:
        raise RuntimeError("calibrated fiducial PnP returned an invalid pose")

    reprojected, _ = cv2.projectPoints(
        _OBJECT_POINTS,
        cv2.Rodrigues(rotation_camera_from_tag)[0],
        translation,
        intrinsic,
        np.zeros((4, 1), dtype=np.float64),
    )
    residual = np.linalg.norm(reprojected.reshape(-1, 2) - image_points, axis=1)
    reprojection_error = float(np.sqrt(np.mean(np.square(residual))))
    reprojection_limit = 4.0 if depth_fit_rms is not None else 2.0
    if not np.isfinite(reprojection_error) or reprojection_error > reprojection_limit:
        raise RuntimeError(
            f"fiducial reprojection error {reprojection_error:.3f} px exceeds {reprojection_limit:.1f} px"
        )

    perimeter = float(cv2.arcLength(image_points.astype(np.float32), True))
    size_score = min(1.0, perimeter / 100.0)
    confidence = float(np.clip(size_score * np.exp(-0.5 * reprojection_error), 0.0, 1.0))
    return FiducialPose(position, rotation, image_points, reprojection_error, confidence)


__all__ = [
    "FIDUCIAL_DICTIONARY",
    "FIDUCIAL_MARKER_ID",
    "FIDUCIAL_QUIET_ZONE_SIZE_M",
    "FIDUCIAL_TAG_BITS",
    "FIDUCIAL_TAG_BASIS_MODULE",
    "FIDUCIAL_TAG_CENTER_M",
    "FIDUCIAL_TAG_ROTATION_MODULE_FROM_TAG_WXYZ",
    "FIDUCIAL_TAG_SIZE_M",
    "FiducialPose",
    "estimate_fiducial_pose",
]
