"""The paired arm and module poses an insertion may start from.

Generated by ``scripts/solve_insert_reset_bank.py``; do not hand-edit. Each
entry is one axial station along the seating stroke and the arm
configuration that presents the pin's grip point there, solved in closed
form by ``zero_g_blade_swap.arm_kinematics`` and gated on residual, on the
DLS controller's realised authority, and on the collar staying clear of the
rack mouth. ``evidence/insert_reset_bank.json`` records all of it.
"""

from __future__ import annotations

#: Shallow end first: the module centre the transit hands over at, through
#: to the certified staging pose the single-pose reset used.
#:
#: One row, and one bay. The chain seats into the second bay with the robot
#: parked opposite it on the lateral rail, and parked there the arm's
#: configuration is bit-identical to the one it has at bay 1 -- solved both
#: ways, the worst joint differs by 0.0000 mrad. Reaching the same bay from
#: the *first* bay's base instead, which is what this bank used to train,
#: differs by 505 mrad. A second row of those is not a second bay, it is a
#: pose the chain never presents.
INSERT_STROKE_ARM_JOINT_POS = (
    (
        (-0.99794, -2.362859, 2.648292, 2.855897, -0.573046, -1.570581),
        (-0.728012, -2.112343, 2.57599, 2.677817, -0.842805, -1.570707),
        (-0.583196, -1.940423, 2.496875, 2.585093, -0.987592, -1.570383),
        (-0.488971, -1.804165, 2.412519, 2.533195, -1.081817, -1.570392),
        (-0.421895, -1.688878, 2.32379, 2.506653, -1.148917, -1.570774),
        (-0.371472, -1.587086, 2.231121, 2.497534, -1.199284, -1.570783),
        (-0.331999, -1.494336, 2.134633, 2.501279, -1.238795, -1.57078),
        (-0.30025, -1.407683, 2.034212, 2.515051, -1.270538, -1.570781),
        (-0.274131, -1.325029, 1.929532, 2.537075, -1.296616, -1.570788),
    ),
)

INSERT_STROKE_BLADE_POSE = (
    (
        (0.146753, -0.22, 0.72, 1.0, 0.0, 0.0, 0.0),
        (0.201271, -0.22, 0.72, 1.0, 0.0, 0.0, 0.0),
        (0.25579, -0.22, 0.72, 1.0, 0.0, 0.0, 0.0),
        (0.310308, -0.22, 0.72, 1.0, 0.0, 0.0, 0.0),
        (0.364826, -0.22, 0.72, 1.0, 0.0, 0.0, 0.0),
        (0.419345, -0.22, 0.72, 1.0, 0.0, 0.0, 0.0),
        (0.473863, -0.22, 0.72, 1.0, 0.0, 0.0, 0.0),
        (0.528382, -0.22, 0.72, 1.0, 0.0, 0.0, 0.0),
        (0.5829, -0.22, 0.72, 1.0, 0.0, 0.0, 0.0),
    ),
)

__all__ = ["INSERT_STROKE_ARM_JOINT_POS", "INSERT_STROKE_BLADE_POSE"]
