params:
  seed: 42
  env:
    clip_observations: 10.0
    clip_actions: 1.0
    obs_groups:
      obs: [policy]
      states: []
    concate_obs_groups: true
  algo:
    name: a2c_continuous
  model:
    name: continuous_a2c_logstd
  network:
    name: blade_swap_teacher
    mlp:
      units: [256, 256, 128]
      activation: elu
      initializer: {name: default}
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init: {name: default}
        sigma_init: {name: const_initializer, val: -0.5}
        fixed_sigma: true
  load_checkpoint: false
  load_path: ""
  config:
    name: zero_g_blade_insertion_robust
    env_name: rlgpu
    device: cuda:0
    device_name: cuda:0
    multi_gpu: false
    ppo: true
    mixed_precision: true
    normalize_input: true
    normalize_value: true
    value_bootstrap: true
    num_actors: -1
    reward_shaper: {scale_value: 1.0}
    normalize_advantage: true
    gamma: 0.99
    tau: 0.95
    learning_rate: 3.0e-4
    lr_schedule: adaptive
    schedule_type: standard
    kl_threshold: 0.008
    max_epochs: 2500
    save_best_after: 50
    save_frequency: 100
    print_stats: true
    grad_norm: 1.0
    entropy_coef: 0.005
    truncate_grads: true
    e_clip: 0.2
    horizon_length: 32
    minibatch_size: 4096
    mini_epochs: 4
    critic_coef: 2.0
    clip_value: true
    seq_length: 4
    bounds_loss_coef: 0.0001
    player:
      deterministic: true
      print_stats: true
